### YamlMime:Sample
sample:
- name: Print auto-configuration sample
  description: Demonstrates how to implement auto-configuration in v4 print drivers.
  generateZip: true
  preserveParentHierarchy: true
  author: windows-driver-samples
  languages:
  - cpp
  technologies:
  - windows
  vssolution: /Windows-driver-samples/print/autoconfig/AutoConfig.sln
