name: Build changes to driver samples
on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
jobs:
  build:
    name: Build driver samples
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install WDK VSIX
        run: .\.github\scripts\Install-Vsix.ps1

      - name: Install Nuget Packages
        run: nuget restore .\packages.config -PackagesDirectory .\packages\

      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@v41
        with:
          separator: ","

      - name: Retrieve and build solutions from changed files
        run: |
          $changedFiles = "${{ steps.get-changed-files.outputs.all_changed_files }}".Split(',')
          .\.github\scripts\Build-ChangedSamples.ps1 -ChangedFiles $changedFiles -Verbose
        env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}

      - name: Archive build logs and overview build reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: _logs
  
  report:
    name: Generate global report
    runs-on: windows-2022
    needs: build
    if: always()
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Retrieve overview reports
        uses: actions/download-artifact@v3
        with:
          name: logs
          path: _logs

      - name: Join and generate global reports
        run: .\.github\scripts\Join-CsvReports.ps1

      - name: Archive global overview build reports
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: _logs/_overview.all.*
